--
-- Table structure for table `T_CONTINENT_TCT`
--
DROP TABLE IF EXISTS `T_CONTINENT_TCT`;
CREATE TABLE `T_CONTINENT_TCT`(
        `TCT_ID` int (11) Auto_increment  NOT NULL ,
	`TCT_NAME` varchar(30) NOT NULL,
        PRIMARY KEY (`TCT_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;


--
-- Table structure for table `T_COUNTRY_TCY`
--
DROP TABLE IF EXISTS `T_COUNTRY_TCY`;
CREATE TABLE IF NOT EXISTS `T_COUNTRY_TCY` (
  `TCY_ID` smallint(5) unsigned NOT NULL AUTO_INCREMENT,
  `TCY_CODE` int(3) NOT NULL,
  `TCY_ALPHA2` varchar(2) NOT NULL,
  `TCY_ALPHA3` varchar(3) NOT NULL,
  `TCY_EN_GB_NAME` varchar(45) NOT NULL,
  `TCY_FR_FR_NAME` varchar(45) NOT NULL,
  `TCT_ID` int(11) NOT NULL,
  PRIMARY KEY (`TCY_ID`),
  KEY `FK_T_COUNTRY_TCY_TCT_ID` (`TCT_ID`),
  UNIQUE KEY `TCY_ALPHA2` (`TCY_ALPHA2`),	
  UNIQUE KEY `TCY_ALPHA3` (`TCY_ALPHA3`),
  UNIQUE KEY `TCY_CODE` (`TCY_CODE`),
  CONSTRAINT `FK_T_COUNTRY_TCY_TCT_ID` FOREIGN KEY (`TCT_ID`) REFERENCES `T_CONTINENT_TCT` (`TCT_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

