USE `iam_bcom`;

ALTER TABLE `T_PERSON_PRS` DROP FOREIGN KEY `FK_T_PERSON_PRS_TTO_ID`;
ALTER TABLE `T_PERSON_PRS` DROP `TTO_ID`;

DROP PROCEDURE IF EXISTS `add_country`;
DROP PROCEDURE IF EXISTS `bind_event_type_2_scope`;
DROP PROCEDURE IF EXISTS `get_scopes_for_event_type`;
DROP PROCEDURE IF EXISTS `add_travel_wf_role`;
DROP PROCEDURE IF EXISTS `get_travel_validation_roles`;
DROP PROCEDURE IF EXISTS `get_travel_notified_roles`;
DROP PROCEDURE IF EXISTS `get_directors_except`;
DROP PROCEDURE IF EXISTS `add_event`;
DROP PROCEDURE IF EXISTS `add_concrete_event`;
DROP PROCEDURE IF EXISTS `add_template_event`;
DROP PROCEDURE IF EXISTS `add_address`;
DROP FUNCTION IF EXISTS `addAddress`;

DROP TABLE IF EXISTS `R_ATTENDEES_RAS`;
DROP TABLE IF EXISTS `R_INIT`;
DROP TABLE IF EXISTS `R_INVOLVED_ROLES`;
DROP TABLE IF EXISTS `R_PRS_THL_TMN`;
DROP TABLE IF EXISTS `R_PRS_TRT_TST`;
DROP TABLE IF EXISTS `R_TET_TEA`;
DROP TABLE IF EXISTS `R_THG_TLC`;
DROP TABLE IF EXISTS `R_TMN_TET`;
DROP TABLE IF EXISTS `R_TMN_TTP_TTN_TTL`;
DROP TABLE IF EXISTS `R_TST_TMN`;
DROP TABLE IF EXISTS `R_TTN_TLC`;
DROP TABLE IF EXISTS `R_TTO_TLC`;
DROP TABLE IF EXISTS `R_TTY_TES_CONSTRAINT`;
DROP TABLE IF EXISTS `travel_event`;
DROP VIEW IF EXISTS `travel_event`;

ALTER TABLE `T_EVENT_ADDRESS_TEA` DROP FOREIGN KEY `FK_T_EVENT_ADDRESS_TEA_TAS_ID`;
ALTER TABLE `T_HOSTING_LOCATION_THL` DROP FOREIGN KEY `FK_T_HOSTING_LOCATION_THL_THG_ID`;
ALTER TABLE `T_HOSTING_LOCATION_THL` DROP FOREIGN KEY `FK_T_HOSTING_LOCATION_THL_TAS_ID`;
ALTER TABLE `T_ADDRESS_TAS` DROP FOREIGN KEY `FK_T_ADDRESS_TAS_TCY_ID`;
ALTER TABLE `T_COUNTRY_TCY` DROP FOREIGN KEY `FK_T_COUNTRY_TCY_CTT_ID`;
ALTER TABLE `T_CONCRETE_EVENT_TCT` DROP FOREIGN KEY `FK_T_CONCRETE_EVENT_TCT_PRS_ID_AUTHOR`;
ALTER TABLE `T_CONCRETE_EVENT_TCT` DROP FOREIGN KEY `FK_T_CONCRETE_EVENT_TCT_TRT_ID`;
ALTER TABLE `T_CONCRETE_EVENT_TCT` DROP FOREIGN KEY `FK_T_CONCRETE_EVENT_TCT_PRS_ID_LEADER`;
ALTER TABLE `T_CONCRETE_EVENT_TCT` DROP FOREIGN KEY `FK_T_CONCRETE_EVENT_TCT_TAS_ID`;
ALTER TABLE `T_CONCRETE_EVENT_TCT` DROP FOREIGN KEY `FK_T_CONCRETE_EVENT_TCT_TET_ID`;
ALTER TABLE `T_EVENT_TET` DROP FOREIGN KEY `FK_T_EVENT_TET_TTY_ID`;
ALTER TABLE `T_EVENT_TET` DROP FOREIGN KEY `FK_T_EVENT_TET_TES_ID`;
ALTER TABLE `T_MISSION_TMN` DROP FOREIGN KEY `FK_T_MISSION_TMN_PRS_ID`;
ALTER TABLE `T_TRAVEL_LOCATION_TTL` DROP FOREIGN KEY `FK_T_TRAVEL_LOCATION_TTL_TAS_ID`; 

DROP TABLE IF EXISTS `T_ADDRESS_TAS`;
DROP TABLE IF EXISTS `T_CONCRETE_EVENT_TCT`;
DROP TABLE IF EXISTS `T_CONTINENT_CTT`;
DROP TABLE IF EXISTS `T_COUNTRY_TCY`;
DROP TABLE IF EXISTS `T_EVENT_ADDRESS_TEA`;
DROP TABLE IF EXISTS `T_EVENT_SCOPE_TES`;
DROP TABLE IF EXISTS `T_EVENT_TET`;
DROP TABLE IF EXISTS `T_EVENT_TYPE_TTY`;
DROP TABLE IF EXISTS `T_HOSTING_LOCATION_THL`;
DROP TABLE IF EXISTS `T_HOSTING_THG`;
DROP TABLE IF EXISTS `T_INVOLVEMENT_NATURE_TIN`;
DROP TABLE IF EXISTS `T_LOYALTY_CARD_TLC`;
DROP TABLE IF EXISTS `T_MISSION_TMN`;
DROP TABLE IF EXISTS `T_PRS_TRAVEL_INFO_TTO`;
DROP TABLE IF EXISTS `T_PURPOSE_TPE`;
DROP TABLE IF EXISTS `T_REPORT_TRT`;
DROP TABLE IF EXISTS `T_STATUS_TST`;
DROP TABLE IF EXISTS `T_TRANSPORT_NATURE_TTN`;
DROP TABLE IF EXISTS `T_TRAVEL_LOCATION_TTL`;
DROP TABLE IF EXISTS `T_TRIP_TTP`;


